### ISSUE TITLE
./autogen.sh: line 13: autoreconf: command not found

### ISSUE THREAD

**Issue by HatsuneMikuV** [yiyangest/ijkplayer-speex#1]
./compile-speexdsp.sh all
====================
[*] check xcode version
====================
FF_ALL_ARCHS = armv7 arm64
====================
[*] check host
====================
build_root: /Users/mt/Desktop/qazxwws/ijkplayer-speex/ios
====================
[*] config arch armv7
====================
build_name: speexdsp-armv7
platform:   iPhoneOS
osversion:  -miphoneos-version-min=6.0
====================
[*] make ios toolchain speexdsp-armv7
====================
build_source: /Users/mt/Desktop/qazxwws/ijkplayer-speex/ios/speexdsp-armv7
build_prefix: /Users/mt/Desktop/qazxwws/ijkplayer-speex/ios/build/speexdsp-armv7/output
CROSS_TOP: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer
CROSS_SDK: iPhoneOS10.2.sdk
BUILD_TOOL: /Applications/Xcode.app/Contents/Developer
CC: xcrun -sdk iphoneos clang -arch armv7 -miphoneos-version-min=6.0

--------------------
[*] configurate speexdsp
--------------------
should run autogen.sh first
Updating build configuration files, please wait....
./autogen.sh: line 13: autoreconf: command not found

**Comment by yiyangest** [comment]
run ` brew install automake` to try again

**Comment by HatsuneMikuV** [comment]
--------------------
[*] configurate ogg
--------------------
should run autogen.sh first
config: --host=arm-apple-darwin  --prefix=/Users/mt/Desktop/qazxwws/ijkplayer-speex-master/ios/build/ogg-armv7/output
checking for autoconf... 
-n checking for automake 1.11 or later... 
automake
-n checking for aclocal 1.11 or later... 
aclocal
-n checking for libtool... 
nope.

You must have libtool installed to compile libogg.
Download the appropriate package for your system,
or get the source from one of the GNU ftp sites
listed in http://www.gnu.org/order/ftp.html

**Comment by HatsuneMikuV** [comment]
Thank you !  I have been solved.
